<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-JOQ5JFT" name="com.eco.tests.PDPPageTest" tests="10" failures="1" timestamp="2022-12-26T11:13:47 IST" time="14.310" errors="0">
  <testcase name="validateProductImage1HeightTest" time="0.018" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
  <testcase name="validateProductBrewingTest" time="2.034" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
  <testcase name="validateProductImage1WidthTest" time="0.014" classname="com.eco.tests.PDPPageTest">
    <failure type="java.lang.AssertionError" message="expected [381] but found [380]">
      <![CDATA[java.lang.AssertionError: expected [381] but found [380]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.eco.tests.PDPPageTest.validateProductImage1WidthTest(PDPPageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateProductImage1WidthTest -->
  <system-out/>
  <testcase name="validateCupImageHeightTest" time="0.041" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
  <testcase name="validateSustainabilityTitleTest" time="2.037" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
  <testcase name="validateProductDescriptionTest" time="2.027" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
  <testcase name="validateProductIntensityTest" time="2.040" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
  <testcase name="validateProductTasteTest" time="2.047" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
  <testcase name="validateCupImageWidthTest" time="0.017" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
  <testcase name="validateProductTitleTest" time="4.035" classname="com.eco.tests.PDPPageTest"/>
  <system-out/>
</testsuite> <!-- com.eco.tests.PDPPageTest -->
